export type Severity = 'high' | 'medium' | 'low'

export interface SpamWord {
  word: string
  severity: Severity
  suggestion: string
}

export const spamWords: SpamWord[] = [
  // ── High severity ─────────────────────────────────────
  { word: 'free', severity: 'high', suggestion: 'at no extra cost' },
  { word: 'act now', severity: 'high', suggestion: 'when you get a chance' },
  { word: 'limited time', severity: 'high', suggestion: 'available through [specific date]' },
  { word: 'buy now', severity: 'high', suggestion: 'get started today' },
  { word: 'order now', severity: 'high', suggestion: 'place your order when ready' },
  { word: 'click here', severity: 'high', suggestion: 'see the details here' },
  { word: 'click below', severity: 'high', suggestion: 'I linked it below' },
  { word: 'urgent', severity: 'high', suggestion: 'time-sensitive' },
  { word: 'congratulations', severity: 'high', suggestion: 'great news' },
  { word: 'winner', severity: 'high', suggestion: 'you were selected' },
  { word: 'you have been selected', severity: 'high', suggestion: 'we thought you would be a great fit' },
  { word: 'risk free', severity: 'high', suggestion: 'with a full refund policy' },
  { word: 'risk-free', severity: 'high', suggestion: 'with a full refund policy' },
  { word: 'no obligation', severity: 'high', suggestion: 'no pressure at all' },
  { word: 'guarantee', severity: 'high', suggestion: 'we stand behind it' },
  { word: 'guaranteed', severity: 'high', suggestion: 'we are confident you will see results' },
  { word: 'no cost', severity: 'high', suggestion: 'included with your plan' },
  { word: 'double your', severity: 'high', suggestion: 'significantly grow your' },
  { word: 'earn money', severity: 'high', suggestion: 'generate additional revenue' },
  { word: 'make money', severity: 'high', suggestion: 'build a revenue stream' },
  { word: 'cash bonus', severity: 'high', suggestion: 'performance incentive' },
  { word: 'million dollars', severity: 'high', suggestion: 'significant growth' },
  { word: 'be your own boss', severity: 'high', suggestion: 'run your own operation' },
  { word: 'work from home', severity: 'high', suggestion: 'remote-friendly setup' },
  { word: 'no experience', severity: 'high', suggestion: 'no prior background needed' },
  { word: 'apply now', severity: 'high', suggestion: 'reach out if interested' },
  { word: 'sign up free', severity: 'high', suggestion: 'create your account' },
  { word: 'unsubscribe', severity: 'high', suggestion: 'opt out anytime' },
  { word: 'as seen on', severity: 'high', suggestion: 'featured by' },
  { word: 'lowest price', severity: 'high', suggestion: 'very competitive pricing' },
  { word: '100% free', severity: 'high', suggestion: 'no charge to get started' },
  { word: 'act immediately', severity: 'high', suggestion: 'at your earliest convenience' },
  { word: 'dear friend', severity: 'high', suggestion: 'Hi [first name]' },
  { word: 'no credit card', severity: 'high', suggestion: 'no payment info needed upfront' },
  { word: 'this is not spam', severity: 'high', suggestion: '[remove entirely]' },
  { word: 'you won', severity: 'high', suggestion: '[remove entirely]' },

  // ── Medium severity ───────────────────────────────────
  { word: 'deal', severity: 'medium', suggestion: 'arrangement' },
  { word: 'offer', severity: 'medium', suggestion: 'option we put together' },
  { word: 'discount', severity: 'medium', suggestion: 'reduced rate' },
  { word: 'cheap', severity: 'medium', suggestion: 'cost-effective' },
  { word: 'bargain', severity: 'medium', suggestion: 'solid value' },
  { word: 'bonus', severity: 'medium', suggestion: 'added benefit' },
  { word: 'exclusive', severity: 'medium', suggestion: 'early access' },
  { word: 'special promotion', severity: 'medium', suggestion: 'something we are running right now' },
  { word: 'limited offer', severity: 'medium', suggestion: 'currently available' },
  { word: 'once in a lifetime', severity: 'medium', suggestion: 'a rare chance' },
  { word: 'don\'t miss', severity: 'medium', suggestion: 'worth looking into' },
  { word: 'don\'t delete', severity: 'medium', suggestion: '[remove entirely]' },
  { word: 'increase sales', severity: 'medium', suggestion: 'grow your pipeline' },
  { word: 'increase traffic', severity: 'medium', suggestion: 'drive more qualified visitors' },
  { word: 'opt in', severity: 'medium', suggestion: 'join us' },
  { word: 'subscribe', severity: 'medium', suggestion: 'stay in the loop' },
  { word: 'call now', severity: 'medium', suggestion: 'happy to hop on a call' },
  { word: 'compare rates', severity: 'medium', suggestion: 'see how we stack up' },
  { word: 'save big', severity: 'medium', suggestion: 'cut your costs' },
  { word: 'save money', severity: 'medium', suggestion: 'reduce your spend' },
  { word: 'best price', severity: 'medium', suggestion: 'strong value' },
  { word: 'lowest rates', severity: 'medium', suggestion: 'competitive rates' },
  { word: 'no hidden', severity: 'medium', suggestion: 'fully transparent' },
  { word: 'no fees', severity: 'medium', suggestion: 'everything is included' },
  { word: 'no catch', severity: 'medium', suggestion: 'straightforward terms' },
  { word: 'no strings', severity: 'medium', suggestion: 'simple and clear' },
  { word: 'instant access', severity: 'medium', suggestion: 'access right away' },
  { word: 'instant results', severity: 'medium', suggestion: 'see results quickly' },
  { word: 'amazing', severity: 'medium', suggestion: 'impressive' },
  { word: 'incredible', severity: 'medium', suggestion: 'really strong' },
  { word: 'revolutionary', severity: 'medium', suggestion: 'a fresh approach' },
  { word: 'breakthrough', severity: 'medium', suggestion: 'a meaningful improvement' },
  { word: 'money back', severity: 'medium', suggestion: 'full refund if not a fit' },
  { word: 'satisfaction guaranteed', severity: 'medium', suggestion: 'we will make it right' },
  { word: 'while supplies last', severity: 'medium', suggestion: 'while spots are open' },

  // ── Low severity ──────────────────────────────────────
  { word: 'opportunity', severity: 'low', suggestion: 'usually fine — use sparingly' },
  { word: 'promotion', severity: 'low', suggestion: 'usually fine — use sparingly' },
  { word: 'solution', severity: 'low', suggestion: 'try being more specific about what you solve' },
  { word: 'introducing', severity: 'low', suggestion: 'usually fine — use sparingly' },
  { word: 'announcing', severity: 'low', suggestion: 'usually fine — use sparingly' },
  { word: 'improve', severity: 'low', suggestion: 'usually fine — use sparingly' },
  { word: 'help', severity: 'low', suggestion: 'usually fine — use sparingly' },
  { word: 'reminder', severity: 'low', suggestion: 'usually fine — use sparingly' },
  { word: 'follow up', severity: 'low', suggestion: 'circling back' },
  { word: 'following up', severity: 'low', suggestion: 'circling back on this' },
  { word: 'checking in', severity: 'low', suggestion: 'wanted to touch base' },
  { word: 'quick question', severity: 'low', suggestion: 'one thing I was curious about' },
  { word: 'partnership', severity: 'low', suggestion: 'working together' },
  { word: 'collaborate', severity: 'low', suggestion: 'team up' },
  { word: 'scale', severity: 'low', suggestion: 'usually fine — use sparingly' },
  { word: 'roi', severity: 'low', suggestion: 'usually fine — use sparingly' },
  { word: 'leverage', severity: 'low', suggestion: 'use / take advantage of' },
]
